const router = require('./node_modules/koa-router')()
const Query = require('./routers/Query')
const Catcher = require('./routers/Catcher')
const Like = require('./routers/Like')
const Clientjs = require('./routers/Clientjs')
router.use(Query)
router.use(Catcher)
router.use(Like)
router.use(Clientjs)
module.exports = router.routes()